[workspace]
members = [
    "contracts/stream",
    "contracts/invoice",
    "contracts/subscription",
]

[workspace.dependencies]
soroban-sdk = "21.0.0"
soroban-sdk-macros = "21.0.0"
stellar-sdk = "0.24.0"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
