[package]
name = "web3-suite-payment-stream"
version = "0.1.0"
edition = "2021"
description = "Soroban smart contract for continuous payment streams"
license = "MIT"
repository = "https://github.com/sudo-robi/web3-suite-payments-contracts"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils" ] }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
